# Conexión a MongoDB Atlas
# INSTRUCCIÓN: Reemplaza la URI con los datos de tu cluster de MongoDB Atlas.
# Formato: mongodb+srv://<usuario>:<password>@<cluster>.mongodb.net/<database>?retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb+srv://230110337_db_user:Dt2tSJDsDf8ACLZn@clusteritsoeh.yvaycta.mongodb.net/gymtrackdb?retryWrites=true&w=majority&appName=ClusterITSOEH
spring.data.mongodb.auto-index-creation=true

# Configuración del servidor
server.port=8080
